# Generated by Django 5.1.1 on 2024-12-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del evento')),
                ('descr', models.CharField(max_length=200, verbose_name='Descripcion del evento')),
                ('cuando', models.DateField(verbose_name='Fecha del evento')),
                ('solidarios', models.IntegerField(verbose_name='Creditos solidarios')),
                ('culturales', models.IntegerField(verbose_name='Creditos culturales')),
                ('deportivos', models.IntegerField(verbose_name='Creditos deportivos')),
                ('fechaCreacion', models.DateTimeField(verbose_name='Fecha y hora de creacion')),
                ('horaInicio', models.CharField(max_length=10, verbose_name='Hora de inicio')),
                ('horaFin', models.CharField(max_length=10, verbose_name='Hora de finalizacion')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
