# Generated by Django 5.1.1 on 2024-12-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(default='./static/images/imagen_default_evento_.webp', upload_to='imagenes_eventos/'),
        ),
    ]
