# Generated by Django 5.1.1 on 2024-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(default='imagenes_eventos/imagen_default_evento.webp', upload_to='imagenes_eventos/'),
        ),
    ]
