# Generated by Django 5.1.1 on 2024-12-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='idUsuario',
        ),
    ]
