# Generated by Django 5.1.1 on 2024-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='requisitos',
            field=models.CharField(default=None, max_length=400, verbose_name='Requisitos para el evento'),
            preserve_default=False,
        ),
    ]
