# Generated by Django 5.1.1 on 2024-12-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_evento_fechacreacion_alter_evento_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='culturales',
            field=models.IntegerField(default=0, verbose_name='Creditos culturales'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='deportivos',
            field=models.IntegerField(default=0, verbose_name='Creditos deportivos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='requisitos',
            field=models.CharField(default='Sin requisitos', max_length=400, verbose_name='Requisitos para el evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='solidarios',
            field=models.IntegerField(default=0, verbose_name='Creditos solidarios'),
        ),
    ]
