# Generated by Django 5.1.1 on 2024-12-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_evento_culturales_alter_evento_deportivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horaFin',
            field=models.TimeField(max_length=10, verbose_name='Hora de finalizacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horaInicio',
            field=models.TimeField(max_length=10, verbose_name='Hora de inicio'),
        ),
    ]
