# Generated by Django 5.1.1 on 2024-12-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('registros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='Registro',
        ),
    ]
