# Generated by Django 5.1.1 on 2024-12-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_registros_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='asistencia',
            field=models.BooleanField(default=0, verbose_name='Asistencia al evento'),
        ),
    ]
