# Generated by Django 5.1.1 on 2024-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña del usuario')),
                ('superUser', models.BooleanField(default=False, verbose_name='Es cuenta de adminsitrador')),
            ],
        ),
    ]
