# Generated by Django 5.1.1 on 2024-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(default='', max_length=50, verbose_name='Carrera del usuario'),
        ),
    ]
