# Generated by Django 5.1.1 on 2024-12-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Es cuenta de adminsitrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(default='', max_length=20, verbose_name='Carrera del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='superUser',
            field=models.BooleanField(default=False, verbose_name='Es cuenta de Super usuario'),
        ),
    ]
