# Generated by Django 5.1.1 on 2024-12-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Contraseña del usuario'),
        ),
    ]
